ktor {
  deployment {
    port = 8080
  }
  application {
    modules = [org.cyoda.example.webserver.WebServerKt.module]
  }
  session {
    cookie-encrypt-key = "435599b574207de56f93349c4c281941"
    cookie-sign-key = "7bd29e325d33145582fd08dc5728d80bf20481f6f81395238f76c1c486f8d939"
  }
}

app {
  processors = ["NobelPrizeMessageDissector"]
}

cyoda {
  connection {
    api-url = "http://localhost:8082/api"
    grpc-server = "localhost"
    grpc-server-port = 50051
    grpc-server-use-tls = false
  }
}